# Generated by Django 4.0.6 on 2022-08-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carbs', models.FloatField(max_length=100)),
                ('protein', models.FloatField(max_length=100)),
                ('fats', models.FloatField(max_length=100)),
                ('calories', models.FloatField(max_length=100)),
            ],
        ),
    ]
